spring:
  data:
    mongodb:
      uri : mongodb+srv://admin:Admin123@studentattendance.xutfpxe.mongodb.net/
      database : Students-Attendance-System

  smtp:
    host: smtp.gmail.com
    port: 587
    username: studattendsys@gmail.com
    password: qbqtpjcwyyqyqowf

server:
  port: 8080
